model:
  model_id: game_rft_audio
  sample_size: 4
  channels: 128
  audio_channels: 64
  
  n_layers: 24
  n_heads: 24
  d_model: 1536

  tokens_per_frame: 17
  n_buttons: 11
  n_mouse_axes: 2

  cfg_prob: 0.0
  n_frames: 60

  causal: true

train:
  trainer_id: sforce2
  data_id: cod_s3_audio
  data_kwargs:
    window_length: 60
    bucket_name: cod-data-latent-360x640to4x4
    prefix: labelled
    file_share_max: 50

  sample_data_id: cod_s3_audio
  sample_data_kwargs:
    window_length: 60
    bucket_name: cod-data-latent-360x640to4x4
    prefix: labelled
    file_share_max: 50

  target_batch_size: 4
  batch_size: 4

  epochs: 200

  opt: AdamW
  opt_kwargs:
    lr: 2.0e-6
    betas: [0.0, 0.999]
    weight_decay: 0.01
    eps: 1.0e-8
  d_opt_kwargs:
    lr: 4.0e-7
    betas: [0.0, 0.999]
    weight_decay: 0.01
    eps: 1.0e-8
    
  scheduler: null

  checkpoint_dir: /mnt/data/shahbuland/checkpoints/av_v2_sf
  output_path: /mnt/data/shahbuland/checkpoints/av_v2_sf_output
  resume_ckpt: null #checkpoints/av_v2/step_30000.pt
        
  sample_interval: 200
  save_interval: 500

  sampler_id: av_caching
  sampler_kwargs:
    n_steps: 3
    num_frames: 60
    window_length: 60
    only_return_generated: false

  n_samples: 4

  vae_id: null
  vae_batch_size: 4
  vae_scale: 0.7
  audio_vae_scale: 0.45

  vae_cfg_path: configs/owl_vaes/cod_128x.yml
  vae_ckpt_path: /mnt/data/checkpoints/cache_for_wm/sf_v0/cod_128x_rgb.pt

  audio_vae_id: null
  audio_vae_cfg_path: configs/owl_vaes/audio_ae_2.yml
  audio_vae_ckpt_path: /mnt/data/checkpoints/cache_for_wm/sf_v0/cod_audio.pt

  teacher_ckpt: /mnt/data/checkpoints/cache_for_wm/sf_v0/causal_teacher.pt
  student_ckpt: /mnt/data/checkpoints/cache_for_wm/sf_v0/causal_teacher.pt

  context_frames: 40

wandb:
  name: shahbuland
  project: video_models
  run_name: av_v2_selfforce